import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/widgets.dart';

String adminText(BuildContext context, String vietnamese) {
  if (context.locale.languageCode != 'en') return vietnamese;
  final exact = _englishTranslations[vietnamese];
  if (exact != null) return exact;
  final orderCount = RegExp(r'^(\d+) đơn$').firstMatch(vietnamese);
  if (orderCount != null) return '${orderCount.group(1)} orders';
  final page = RegExp(r'^Trang (\d+)/(\d+)$').firstMatch(vietnamese);
  if (page != null) return 'Page ${page.group(1)} of ${page.group(2)}';
  final sold = RegExp(r'^Đã bán (\d+) sản phẩm$').firstMatch(vietnamese);
  if (sold != null) return '${sold.group(1)} products sold';
  return vietnamese;
}

const _englishTranslations = <String, String>{
  'Áp dụng': 'Apply',
  'Tài khoản': 'Accounts',
  'Loại tài khoản': 'Account type',
  'Trạng thái duyệt': 'Approval status',
  'Tìm theo tên, email hoặc trang trại': 'Search by name, email, or farm',
  'Không tìm thấy tài khoản nào.': 'No accounts found.',
  'hồ sơ farmer': 'farmer application',
  'Đã từ chối hồ sơ.': 'Application rejected.',
  'Không thể cập nhật hồ sơ. Vui lòng thử lại.':
      'Could not update the application. Please try again.',
  'Không yêu cầu duyệt': 'Not subject to approval',
  'Trang trại': 'Farm',
  'Báo cáo hệ thống': 'System reports',
  'Báo cáo hệ thống HarvestHub': 'HarvestHub system report',
  'Bảng điều khiển': 'Dashboard',
  'Bắt buộc': 'Required',
  'Chi tiêu': 'Spent',
  'Chi tiêu cao nhất': 'Highest spending',
  'Chưa có chợ nông sản nào.': 'No markets yet.',
  'Chưa có danh mục nào.': 'No categories yet.',
  'Chưa có dữ liệu doanh thu': 'No revenue data',
  'Chưa có dữ liệu.': 'No data yet.',
  'Chưa xác định': 'Unknown',
  'Chờ duyệt': 'Pending approval',
  'Chờ xử lý': 'Pending',
  'Chợ': 'Market',
  'Chợ nông sản': 'Farmers markets',
  'Cần xử lý': 'Needs attention',
  'Danh mục': 'Categories',
  'Doanh thu theo chợ': 'Revenue by market',
  'Duyệt': 'Approve',
  'Email/mật khẩu': 'Email/password',
  'Giờ bắt đầu': 'Start time',
  'Giờ kết thúc': 'End time',
  'Giờ kết thúc phải sau giờ bắt đầu': 'End time must be after start time',
  'Hiển thị trên Shop': 'Visible in shop',
  'Hoàn tất': 'Completed',
  'Huỷ': 'Cancel',
  'Khoá tài khoản': 'Lock account',
  'Khách hàng': 'Customers',
  'Khách hàng tích cực': 'Most active customers',
  'Không có nhật ký nào trong khoảng đã chọn.':
      'No activity logs in the selected period.',
  'Không có nông dân nào.': 'No farmers found.',
  'Không có phản hồi nào.': 'No messages found.',
  'Không có sản phẩm phù hợp bộ lọc.':
      'No products match the selected filters.',
  'Không có việc cần xử lý ngay.': 'No pending actions.',
  'Không có đơn hàng phù hợp bộ lọc.': 'No orders match the selected filters.',
  'Không thể cập nhật trạng thái tài khoản.':
      'Could not update account status.',
  'Không thể xuất PDF trên thiết bị này.':
      'PDF export is unavailable on this device.',
  'Đã duyệt hồ sơ và gửi email thông báo.':
      'Application approved and email notification sent.',
  'Đã duyệt hồ sơ nhưng chưa gửi được email thông báo.':
      'Application approved, but the email notification could not be sent.',
  'Không thể duyệt hồ sơ. Vui lòng thử lại.':
      'Could not approve the application. Please try again.',
  'Không tìm thấy khách hàng nào.': 'No customers found.',
  'Không tải được báo cáo — thử lại': 'Could not load report — try again',
  'Không tải được danh mục — thử lại': 'Could not load categories — try again',
  'Không tải được danh sách — thử lại': 'Could not load list — try again',
  'Không tải được dữ liệu.': 'Could not load data.',
  'Không tải được nhật ký — thử lại': 'Could not load audit log — try again',
  'Kinh độ': 'Longitude',
  'Kinh độ từ -180 đến 180': 'Longitude must be between -180 and 180',
  'Lý do ẩn sản phẩm': 'Reason for hiding product',
  'Lọc nhật ký hoạt động': 'Filter activity log',
  'Lọc sản phẩm': 'Filter products',
  'Lọc đơn hàng': 'Filter orders',
  'Mua nhiều nhất': 'Most orders',
  'Mới': 'New',
  'Ngày nhiều đơn': 'Most orders by day',
  'Ngày tham gia': 'Joined',
  'Ngôn ngữ': 'Language',
  'Người thực hiện': 'Actor',
  'Nhật ký hoạt động': 'Audit log',
  'Nông dân': 'Farmers',
  'Nông dân tích cực nhất': 'Most active farmers',
  'Năm': 'Year',
  'Phản hồi liên hệ': 'Contact messages',
  'Quý': 'Quarter',
  'Sản phẩm': 'Products',
  'Sản phẩm bán nhiều nhất': 'Best-selling products',
  'Số lượng': 'Quantity',
  'Số đơn': 'Orders',
  'Số đơn hàng': 'Order count',
  'Sửa chợ nông sản': 'Edit market',
  'Sửa danh mục': 'Edit category',
  'Tháng': 'Month',
  'Tháng nhiều đơn': 'Most orders by month',
  'Thêm': 'Add',
  'Thêm chợ nông sản': 'Add market',
  'Thêm danh mục': 'Add category',
  'Thử lại': 'Retry',
  'Tiếng Việt': 'Vietnamese',
  'Trạng thái': 'Status',
  'Tuần': 'Week',
  'Tên (English)': 'Name (English)',
  'Tên (Tiếng Việt)': 'Name (Vietnamese)',
  'Tên chợ (English)': 'Market name (English)',
  'Tên chợ (Tiếng Việt)': 'Market name (Vietnamese)',
  'Tìm theo tên hoặc email': 'Search by name or email',
  'Tất cả': 'All',
  'Tất cả chợ': 'All markets',
  'Tất cả danh mục': 'All categories',
  'Tất cả người dùng': 'All users',
  'Tất cả nông dân': 'All farmers',
  'Tổng chi tiêu': 'Total spent',
  'Tổng doanh thu': 'Total revenue',
  'Tổng đơn hàng': 'Total orders',
  'Từ chối': 'Reject',
  'Từ ngày': 'From',
  'Vd: nội dung/mô tả vi phạm quy định': 'E.g. describe the policy violation',
  'Vui lòng chọn đủ giờ bắt đầu và kết thúc':
      'Please select both a start and end time',
  'Vui lòng nhập lý do': 'Please enter a reason',
  'Vĩ độ': 'Latitude',
  'Vĩ độ từ -90 đến 90': 'Latitude must be between -90 and 90',
  'Xoá': 'Delete',
  'Xoá danh mục?': 'Delete category?',
  'Xuất PDF': 'Export PDF',
  'Xác nhận ẩn': 'Confirm hide',
  'Đang bán': 'For sale',
  'Đang hoạt động': 'Active',
  'Điện thoại': 'Phone',
  'Đánh dấu đã xử lý': 'Mark as resolved',
  'Đã duyệt': 'Approved',
  'Đã huỷ': 'Cancelled',
  'Đã khóa tài khoản.': 'Account locked.',
  'Đã mở khóa tài khoản.': 'Account unlocked.',
  'Đã tạo báo cáo PDF.': 'PDF report created.',
  'Đã xác nhận': 'Confirmed',
  'Đã xử lý': 'Resolved',
  'Đã ẩn': 'Hidden',
  'Đăng nhập bằng': 'Sign-in method',
  'Đơn cao nhất': 'Largest order',
  'Đơn hàng': 'Orders',
  'Đặt lại': 'Reset',
  'Đến ngày': 'To',
  'Địa chỉ': 'Address',
  'Ẩn': 'Hide',
  'Ẩn sản phẩm': 'Hide product',
  'Tổng doanh thu: {}đ': 'Total revenue: {}',
  'Tổng đơn hàng: {}': 'Total orders: {}',
  'Kỳ báo cáo: {}': 'Reporting period: {}',
  'Đã bán {} sản phẩm': '{} products sold',
  '{} đơn': '{} orders',
  'Về trang chủ': 'Go home',
  'Bạn không có quyền truy cập trang quản trị.':
      'You are not authorized to access the admin area.',
  'Admin kiểm tra': 'Admin preview',
  'Liên hệ': 'Contact messages',
  'Báo cáo': 'Reports',
  'Người mua': 'Buyer',
  'Pending': 'Pending',
  'Confirmed': 'Confirmed',
  'Ready for Pickup': 'Ready for pickup',
  'Completed': 'Completed',
  'Cancelled': 'Cancelled',
  'pending': 'Pending',
  'confirmed': 'Confirmed',
  'ready_for_pickup': 'Ready for pickup',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
  'Doanh thu': 'Revenue',
  'Đồng bộ ngoại tuyến': 'Synced offline',
  'Đăng xuất': 'Log out',
  'Không thể đăng xuất. Vui lòng thử lại.':
      'Could not log out. Please try again.',
};
