// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcrq8RKke6HJoZmmrwAz1u9bIza-9fO_I',
    appId: '1:813757604404:web:a89fcb88689b9eec6d6061',
    messagingSenderId: '813757604404',
    projectId: 'harvesthub-509605',
    authDomain: 'harvesthub-509605.firebaseapp.com',
    storageBucket: 'harvesthub-509605.firebasestorage.app',
    measurementId: 'G-QPHCZ0QF2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZ4AeaIYyTLzZjHj4hsbyGKV5KjzosYI',
    appId: '1:813757604404:android:aec0fac120dec7fe6d6061',
    messagingSenderId: '813757604404',
    projectId: 'harvesthub-509605',
    storageBucket: 'harvesthub-509605.firebasestorage.app',
  );
}
